baseURL = 'https://venkatraman.blog'
languageCode = 'en-us'
title = 'venkatraman.blog'
theme = "hugo-theme-console"

[[module.imports]]
  path = "github.com/mrmierzejewski/hugo-theme-console"

[params]
  description = "Venkatraman's Photo Blog"
  animateStyle = "animate-fade-up" # Animation style for content

[[params.navlinks]]
  name = "Posts"
  url = "/posts/"

[[params.navlinks]]
  name = "Albums"
  url = "/albums/"
